Feature/sl 1/setting
cau-likelion-org/Startlion_Server- pull request #1
Opened 2023-09-03 10:22 UTC by eunsu02

## 티켓
SL-1

## 변경사항
1. 프로젝트 초기 세팅
2. h2 연결
3. mairaDB연결
4. swagger 연결
5. config 패키지 생성
6. timezone 서울로 설정

## 부가설명
h2 & mairaDB 는 application.yml
swagger는 SwaggerConfig
timezone는 TimezoneConfig
그리고 config 들을 모아놓은 config 패키지가 있습니다!

## 고려사항
티켓 번호를 못찾아서 우선 SL-1로 올렸습니다!
develop 브랜치가 없길래 만들었습니다!
추가 되어야할 부분, 수정 되어야할 부분, 부족한 부분 가감없이 그대로 말씀해주시면 감사하겠습니다!

## 그외 스크린샷...

2023-09-03 10:29 UTC, unanchoi requested changes
review 했습니다~!

- SecurityConfig class 정도만 추가해주면 좋을 것 같아요 ㅎㅎ
- 아직 구체적으로 Security를 설정할 필요는 없어서, 우선은 요청 제한 없이 설정해두면 좋을 것 같습니다! 아래 참고 링크 남길게요

[SecurityConfig 참고](https://github.com/GO-SOPT-SOPTKATHON-TEAM4/charm-lonely-server/blob/main/src/main/java/com/sopt/sopkathonproduct/config/SecurityConfig.java)

그리고 PR 제목
[SL-1] Project Initial Setting 이런식으로 작성해주시면 좋을 것 같아요~!

2023-09-03 10:29 UTC, unanchoi commented on build/resources/main/application.yml
> +      matching-strategy: ant_path_matcher
이 property는 포함 시킨 이유가 있을까요? 꼭 필요한 것 같지는 않아서요! ㅎ

2023-09-03 10:29 UTC, unanchoi commented on src/main/java/com/startlion/startlionserver/config/SwaggerConfig.java
> +@RequiredArgsConstructor
해당 어노테이션은 없어도 괜찮을 것 같아요~!

2023-09-03 11:48 UTC, jinyoungpark00 commented on src/main/resources/application.yml
> +      matching-strategy: ant_path_matcher
윤한님 말씀하신 것처럼 여기도 필요 없는건가요?

2023-09-03 12:01 UTC, jinyoungpark00 commented
PR 날릴 때 라벨도 사용하면 좋을 것 같아요~

2023-09-03 14:59 UTC, unanchoi commented on src/main/resources/application.yml
> +      matching-strategy: ant_path_matcher
네네 필요 없을 것 같아요~ ㅎ

2023-09-04 01:03 UTC, eunsu02 commented
넵! 라벨 생성, 제목 수정 완료했습니다~!

2023-09-04 01:49 UTC, eunsu02 commented on src/main/java/com/startlion/startlionserver/config/SwaggerConfig.java
> +@RequiredArgsConstructor
넵! 삭제 완료했습니다!

2023-09-04 10:14 UTC, unanchoi approved these changes
고생하셨습니다~!

2023-09-04 13:29 UTC, jinyoungpark00 approved these changes

2023-09-05 15:14 UTC, merged